name: Test and release when tagged

on: [push]

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: docs
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: pixi run --environment docs docs-build --push
      - run: echo ${{ github.ref_name }}
